"""Añadir campos a centros comerciales y locales2

Revision ID: 1609f0e3cf8b
Revises: 500c77423887
Create Date: 2024-09-08 22:49:43.998487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1609f0e3cf8b'
down_revision: Union[str, None] = '500c77423887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
