"""Añadir campos a centros comerciales y locales

Revision ID: 500c77423887
Revises: 6142ebd9da0d
Create Date: 2024-09-08 22:43:52.371293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500c77423887'
down_revision: Union[str, None] = '6142ebd9da0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('centro_comercial_id', sa.Integer(), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('semana', sa.Integer(), nullable=True),
    sa.Column('lectura_inicial', sa.Float(), nullable=True),
    sa.Column('lectura_final', sa.Float(), nullable=True),
    sa.Column('m3', sa.Float(), nullable=True),
    sa.Column('litros', sa.Float(), nullable=True),
    sa.Column('precio_por_litro_bs', sa.Float(), nullable=True),
    sa.Column('precio_por_litro_dolares', sa.Float(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['centro_comercial_id'], ['centros_comerciales.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumo_id'), 'consumo', ['id'], unique=False)
    op.add_column('centros_comerciales', sa.Column('capacidad_litros', sa.Float(), nullable=True))
    op.add_column('centros_comerciales', sa.Column('detalle', sa.String(length=200), nullable=True))
    op.add_column('centros_comerciales', sa.Column('persona_contacto', sa.String(length=50), nullable=True))
    op.add_column('centros_comerciales', sa.Column('mail_contacto', sa.String(length=100), nullable=True))
    op.add_column('centros_comerciales', sa.Column('telefono_contacto', sa.String(length=100), nullable=True))
    op.add_column('centros_comerciales', sa.Column('fecha_registro', sa.DateTime(), nullable=True))
    op.add_column('centros_comerciales', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('locales', sa.Column('razon_social', sa.String(length=200), nullable=True))
    op.add_column('locales', sa.Column('persona_contacto', sa.String(length=50), nullable=True))
    op.add_column('locales', sa.Column('mail_contacto', sa.String(length=100), nullable=True))
    op.add_column('locales', sa.Column('telefono_contacto', sa.String(length=100), nullable=True))
    op.add_column('locales', sa.Column('fecha_registro', sa.DateTime(), nullable=True))
    op.add_column('locales', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locales', 'status')
    op.drop_column('locales', 'fecha_registro')
    op.drop_column('locales', 'telefono_contacto')
    op.drop_column('locales', 'mail_contacto')
    op.drop_column('locales', 'persona_contacto')
    op.drop_column('locales', 'razon_social')
    op.drop_column('centros_comerciales', 'status')
    op.drop_column('centros_comerciales', 'fecha_registro')
    op.drop_column('centros_comerciales', 'telefono_contacto')
    op.drop_column('centros_comerciales', 'mail_contacto')
    op.drop_column('centros_comerciales', 'persona_contacto')
    op.drop_column('centros_comerciales', 'detalle')
    op.drop_column('centros_comerciales', 'capacidad_litros')
    op.drop_index(op.f('ix_consumo_id'), table_name='consumo')
    op.drop_table('consumo')
    # ### end Alembic commands ###
